<a href="https://colab.research.google.com/github/GlubokovK/ML_tutorials/blob/master/Numpy_tutorial.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#### монтировка Google Drive к файловой системе машины

In [0]:
!apt-get install -y -qq software-properties-common python-software-properties module-init-tools
!add-apt-repository -y ppa:alessandro-strada/ppa 2>&1 > /dev/null
!apt-get update -qq 2>&1 > /dev/null
!apt-get -y install -qq google-drive-ocamlfuse fuse

from google.colab import auth
auth.authenticate_user()
from oauth2client.client import GoogleCredentials
creds = GoogleCredentials.get_application_default()
import getpass
!google-drive-ocamlfuse -headless -id={creds.client_id} -secret={creds.client_secret} < /dev/null 2>&1 | grep URL
vcode = getpass.getpass()
!echo {vcode} | google-drive-ocamlfuse -headless -id={creds.client_id} -secret={creds.client_secret}


!mkdir -p drive
!google-drive-ocamlfuse drive

# Run this cell to mount your Google Drive.
from google.colab import drive
drive.mount('/content/drive')

# NUMPY tutorial

#### векторы

In [0]:
import numpy as np

In [0]:
# создать вектор
x = [[2], [3], [4], [6]]
y = np.array(x)

In [5]:
print(y)

[[2]
 [3]
 [4]
 [6]]


In [6]:
print (x * 5)

[[2], [3], [4], [6], [2], [3], [4], [6], [2], [3], [4], [6], [2], [3], [4], [6], [2], [3], [4], [6]]


In [7]:
print (y * 5) #отличие операции от обычной

[[10]
 [15]
 [20]
 [30]]


In [9]:
print (y ** 2)

[[ 4]
 [ 9]
 [16]
 [36]]


In [10]:
matrix = [[1, 2, 4], [3, 1, 0]]
nd_array = np.array(matrix)
print(matrix)
print(nd_array)
print(nd_array[0][1])

[[1, 2, 4], [3, 1, 0]]
[[1 2 4]
 [3 1 0]]
2


In [11]:
print(np.random.rand())

0.5388182620505214


In [12]:
print(np.random.randn(4))

[ 1.09862498  0.17416863 -0.17182377 -0.6662371 ]


In [13]:
print(np.random.randn(4, 5))

[[ 0.54340227  1.30832309 -0.57694551  1.9431822   0.36725779]
 [ 0.14686766 -0.82068019 -1.51930902  0.12222015 -1.29340524]
 [ 1.19208733  0.88381143  0.48864783  0.52490006 -0.08188405]
 [-2.19648836 -0.42917681 -0.89303428 -0.30740036 -1.08978632]]


In [14]:
print(np.arange(0, 8, 0.1)) # анаолог ф-ии range, с дробным шагом

[0.  0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9 1.  1.1 1.2 1.3 1.4 1.5 1.6 1.7
 1.8 1.9 2.  2.1 2.2 2.3 2.4 2.5 2.6 2.7 2.8 2.9 3.  3.1 3.2 3.3 3.4 3.5
 3.6 3.7 3.8 3.9 4.  4.1 4.2 4.3 4.4 4.5 4.6 4.7 4.8 4.9 5.  5.1 5.2 5.3
 5.4 5.5 5.6 5.7 5.8 5.9 6.  6.1 6.2 6.3 6.4 6.5 6.6 6.7 6.8 6.9 7.  7.1
 7.2 7.3 7.4 7.5 7.6 7.7 7.8 7.9]


In [16]:
print(np.linspace(0, 2, 10))

[0.         0.22222222 0.44444444 0.66666667 0.88888889 1.11111111
 1.33333333 1.55555556 1.77777778 2.        ]


In [17]:
%timeit np.arange(0, 10000)
%timeit range(0, 10000)

The slowest run took 39.22 times longer than the fastest. This could mean that an intermediate result is being cached.
100000 loops, best of 3: 9.35 µs per loop
The slowest run took 5.06 times longer than the fastest. This could mean that an intermediate result is being cached.
1000000 loops, best of 3: 265 ns per loop


In [18]:
# создадим матрицу из следующих столбцов:
q1=[1,1,1,1,1,1]
q2=[2,2,2,2,2,2]
q3=[3,3,3,3,3,3]
Qnp=np.array([q1,q2,q3]).transpose()
print(Qnp)

[[1 2 3]
 [1 2 3]
 [1 2 3]
 [1 2 3]
 [1 2 3]
 [1 2 3]]


In [20]:
#вычисление средних по строкам и столбцам таблицы
a=np.array([[2,2,2],[1,1,1],[1,1,1]])
print(a)
print('Средняя по строкам (axis=1): ',np.mean(a,axis=1))

a=np.array([[2,2,2],[1,1,1],[1,1,1]])
print(a)
print('Средняя по стобцам (axis=0): ',np.mean(a,axis=0))

[[2 2 2]
 [1 1 1]
 [1 1 1]]
Средняя по строкам (axis=1):  [2. 1. 1.]
[[2 2 2]
 [1 1 1]
 [1 1 1]]
Средняя по стобцам (axis=0):  [1.33333333 1.33333333 1.33333333]


In [21]:
# Стандартное отклонение std
a=np.array([[2,2,2],[1,1,1],[1,1,1]])
print(a)
print('Стандартное отклонение std: ',np.std(a,axis=0),'\n')

[[2 2 2]
 [1 1 1]
 [1 1 1]]
Стандартное отклонение std:  [0.47140452 0.47140452 0.47140452] 



In [25]:
#Пример поэлементного деления матрицы на вектор строку

a=np.array([[2,2,2],[1,1,1],[1,1,1]])
b=[2,2,1]
print(a)
print(b)
print('Пример поэлементного деления матрицы на вектор строку')
c=a/b
print(c)

#Пример поэлементного вычитания из матрицы вектор строки
print('Пример поэлементного вычитания из матрицы вектор строки')
one=[1,1,1]
d=c-one
print(d)

[[2 2 2]
 [1 1 1]
 [1 1 1]]
[2, 2, 1]
Пример поэлементного деления матрицы на вектор строку
[[1.  1.  2. ]
 [0.5 0.5 1. ]
 [0.5 0.5 1. ]]
Пример поэлементного вычитания из матрицы вектор строки
[[ 0.   0.   1. ]
 [-0.5 -0.5  0. ]
 [-0.5 -0.5  0. ]]


In [28]:
#как преобразовать строку в стобец
print('строка:')
b=np.ones(4)
print(b)
print(b.shape)

print('столбец:')
b=b.reshape(4,1)
print(b)
print(b.shape)

строка:
[1. 1. 1. 1.]
(4,)
столбец:
[[1.]
 [1.]
 [1.]
 [1.]]
(4, 1)


In [34]:
#как к марице добавть столбец
a=np.array([[2,2,2],[3,3,3],[4,4,4],[5,5,5]])
print('a = \n', a)

b=np.ones(4) # создадим единичную строку
b=b.reshape(4,1) # преобразуем строку в единичный стобец
print('b = \n', b)

c=np.hstack((b,a)) # склеим матрицу и столбец
print('c = \n', c)

a = 
 [[2 2 2]
 [3 3 3]
 [4 4 4]
 [5 5 5]]
b = 
 [[1.]
 [1.]
 [1.]
 [1.]]
c = 
 [[1. 2. 2. 2.]
 [1. 3. 3. 3.]
 [1. 4. 4. 4.]
 [1. 5. 5. 5.]]


In [35]:
# Скалярное произведение (Dot product)
a=np.array([1,1,1,1])
b=np.array([1,1,1,1])
print(np.dot(a,b))

4


In [54]:
# индексы максимальных элементов
a = np.array([1,2,3,4,3,2,1])
a.argmax(axis=0)

3

In [57]:
# создание пустого массива, пустой массив, нулевой массив
x1 = np.empty(shape=(3, 3))
x2 = np.zeros(shape=(4, 4))
print(x1)
print()
print(x2)

[[1.  1.  2. ]
 [0.5 0.5 1. ]
 [0.5 0.5 1. ]]

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
